### ISSUE TITLE
[Feature] Streams toestaan in meerdere collections

### ISSUE THREAD

**Issue by braxshinoa** [hbo-nerds/hbo-nerds.github.io#118]

**Comment by superruudje** [comment]
Om dit mogelijk te maken moeten bij alle items in de data.json de `collection` property omgezet worden naar arrays met daarin de ids van de collection.

Ik kan de website hier al op voorbereiden maar we moeten ook kijken hoe we dit in de UI dan gaan uitwerken.

**Comment by superruudje** [comment]
Dit is mogelijk in v2 door van de `collection` property een array (vb: [1, 2]) te maken. Ook de UI is hier op voorbereid. Ik sluit de issue.
