### ISSUE TITLE
[Feature] verbeteren van het datum filter

### ISSUE THREAD

**Issue by braxshinoa** [hbo-nerds/hbo-nerds.github.io#121]
eigenlijk zoals twitchtracker het heeft met een aparte pagina met elke dag erop zou perfect zijn

**Comment by superruudje** [comment]
Na testen bleek dat de pagina het zwaar had met laden. De heat-maps worden nu async ingeladen en er wordt een korte loading animatie getoond.

**Comment by superruudje** [comment]
Nog wat verbeteringen aangebracht aan de performance (tooltips werken nu anders).
