### ISSUE TITLE
Video pop-out soms consistent leeg

### ISSUE THREAD

**Issue by piccleviccle** [hbo-nerds/hbo-nerds.github.io#195]
Mannen,

Ik heb de laatste tijd sporadisch een probleempie met de site waarbij videos soms weigeren te laden, dit trekt ook door als dezelfde videos bijvoorbeeld toegevoegd wordt aan Liked Videos en daar geopend wordt of via de specifieke deel-link, zoals hier:
![image](https://github.com/user-attachments/assets/311b4a92-95b3-44bb-8751-8d7a8b1e4a1a)
(link: https://lekkerspeuren.nl/item/76c1)
Hier deze zelfde vid na openen:
![image](https://github.com/user-attachments/assets/8f6d3d8f-af15-4069-a646-0d979384947f)

Heb zelf geen patroon kunnen herkennen in bij wat voor vids dit speelt en/of dit per user is of dat dit mogelijk gewoon bij iedereen bij bijv. deze video aan de hand is.  In ieder geval bij de video die ik hier als voorbeeld gebruik persist het probleem ook na het clearen van cookies en cache en een hard refresh + browser herstart. Ook Tampermonkey scripts en uBlock staan allen uit.
Ik gebruik zelf Floorp 11.20.0 (een fork van Firefox) 

Whatever gasten

**Comment by ZotoBro** [comment]
Lekker ff spitballen maar een optie voor bijvoorbeeld 'Kopieeër Twitch link' (en YT uiteraard) voor in de drie-punten dropdown menu zou een lekkere optie zijn en als bonus ook als workaround dienen voor dit soort problemen
