### ISSUE TITLE
[Feature] Zoek opties duidelijk maken

### ISSUE THREAD

**Issue by Sheepolution** [hbo-nerds/hbo-nerds.github.io#7]
Alle woorden worden apart gefilterd. Met quotes ("") kan je zoeken op meerdere woorden aan elkaar.

Titel: "Peter kijkt naar Monkel vs Timon"

`Peter vs Timon` Gevonden ✔️ (Vond de woorden Peter, vs, en Timon)

`"Peter vs Timon"` Eruit gefilterd ❌ (Vond niet de woorden in exact die volgorde)

___

Met minus (-) kan je woorden eruit filteren.

`Peter vs Timon -Monkel` Eruit gefilterd ❌ (Alles met 'monkel' wordt niet meegenomen)

___

De gebruiker moet maar gokken dat deze features bestaan. Ergens moeten we deze opties aan de gebruiker leren.

**Comment by superruudje** [comment]
Ik maak hier even een nieuw issue van.
